[package]
name = "sier-codec"
description = "SIER (Static, runtime Interpreted, Evolutionary, Reflective) Codec"
version = "0.0.1"
edition = "2018"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
license = "MIT"

[dependencies]
blake2 = "0.9.1"
nom = "6.2.1"
